### ISSUE TITLE
Error after install: Failed to instantiate component or class "Rekurzia\Log\PapertrailTarget".

### ISSUE THREAD

**Issue by bryantAXS** [trendyminds/craft-papertrail#2]
**Steps to Recreate:**
- Install plugin
- Access front-end of website.

**Other Relevant Information:**

Craft 3.7.32

**Screenshots:** 

https://capture.dropbox.com/ly1XHQS4p8lgUGWU

**Comment by arifje** [comment]
Same issue!

<img width="904" alt="Screenshot 2022-03-06 at 10 46 04" src="https://user-images.githubusercontent.com/1286410/156917926-3e385fe2-8d8e-4e7a-b97f-bcad20dc113b.png">

**Comment by bryantAXS** [comment]
I'm assuming a package was missing from the composer.json file. Is that something you can add in @darinlarimore?

**Comment by darinlarimore** [comment]
Oops sorry, I'll patch this up right away!

**Comment by darinlarimore** [comment]
This should be resolved!

**Comment by arifje** [comment]
Now I am getting a new error after activating;

![Screenshot 2022-03-08 at 14 42 33](https://user-images.githubusercontent.com/1286410/157250011-4dce6444-31e4-427e-bffb-0ec7d495afaf.png)

**Comment by darinlarimore** [comment]
Got this patched up with a new release! @arifje

**Comment by moorebrett0** [comment]
@darinlarimore - I'm still getting this on a fresh composer require
